name: CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: arduino/setup-protoc@v3
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          file: ./.github/workflows/Dockerfile
          push: true
          tags: bragovo/flux-users:latest
